### ISSUE TITLE
Activity module API not fully implemented

### ISSUE THREAD

**Issue by mudrd8mz** [vidyamantra/moodle-mod_congrea#6]
Some expected functions in lib.php are not implemented - such as `congrea_get_recent_mod_activity()`.

**Comment by mudrd8mz** [comment]
Well, I thought the missing functions would be implemented - not removed from lib.php :-)

I agree it is not top priority but would be good to have the module done correctly.

**Comment by pinky28** [comment]
I was unable to think about any information which we need to display through this function. Maybe someone from community might suggest. Keeping it open.

**Comment by mudrd8mz** [comment]
See what other activity modules (such as those included with the Moodle standard distribution) do there.

**Comment by pinky28** [comment]
As per my understanding, this function return all entries since a given time for specified activity.
Congrea is itself a time-based activity hence implementing this feature has no real use according to me.

Modules like assignment, lesson, quiz, forum which depends completely on user performance and has many entries within a specified time for given activity, implemented this function.

Is it recommended/mandatory for all plugins to implement this function? I see that chat, choice, database, scorm, Survey, wiki etc don't implement it.
