### ISSUE TITLE
auth.php

### ISSUE THREAD

**Issue by mudrd8mz** [vidyamantra/moodle-mod_congrea#8]
I see multiple issues with this. Beside some formal ones (such as naming convention for `mycurlrequest()` function), things like `CURLOPT_SSL_VERIFYHOST = false` or `CURLOPT_SSL_VERIFYPEER = false` looks malicious and potentially dangerous. What is this file for anyway?

**Comment by jgupta** [comment]
You are right. We will fix naming.

VERIFYHOST and VERIFYPEER was set to false because we thought it is ok to relax them in favour of simplicity. We wanted to make it easier for people who will be setting up their own server infrastructure and we wanted that any SSL certificate should just work, even self signed ones. Technically, even self signed certificates are as secured as commercial certificates, it is just that authenticity of domain is not done but then again we thought that auth.php file will run from servers which are more secured environment than user computers. What is your recommendation?

Purpose of this file is add authentication. Auth.php file runs on Moodle server which generates username/password combination and sends it to Congrea server and is also passed to browsers. Congrea associates this combination with key and stores it for short period of time. Browser uses this combination for authentication with Congrea. Aim was that key is never transmitted to browsers and browsers needs something unique from Moodle in order to connect with Congrea. Can this be improved?

**Comment by mudrd8mz** [comment]
I see. OK, that makes sense now. Thanks.
